routes/web.php
<?php

use App\Http\Controllers\AjaxController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MerkController;
use App\Http\Controllers\StatusBarangController;
use App\Http\Controllers\TipeController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\ClusterController;
use App\Http\Controllers\ClusterSystemController;
use App\Http\Controllers\LokasiController;
use App\Http\Controllers\VMwareController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PengadaanController;
use App\Http\Controllers\JenisBarangController;
use App\Http\Controllers\MerkBarangController;
use App\Http\Controllers\JenisVirtualMachineController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\NodeController;
use App\Http\Controllers\NutanixController;
use App\Http\Controllers\OSController;
use App\Http\Controllers\PowerVMController;
use App\Http\Controllers\PowerVMListController;
use App\Http\Controllers\VirtualMachineController;
use App\Models\JenisVirtualMachine;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('');
// });

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/barang-guest', [BarangController::class, 'index'])->name('barang.index');
Route::resource('/virtual-machine', VirtualMachineController::class)->only(['index']);

Route::prefix('hypervisor')->name('hypervisor.')->group(function ()
{
    Route::resource('/vmware', VMwareController::class)->only(['index']);
    Route::resource('/nutanix', NutanixController::class)->only(['index']);
    Route::resource('/powervm/{power_vm_id}/lists', PowerVMListController::class, ['names' => 'powervm.lists'])->only(['index']);
    Route::get('powervm/lists', [PowerVMListController::class, 'show'])->name('powervmlists');
    Route::resource('/powervm', PowerVMController::class)->only(['index']);
    // Route::resource('/powervm/list', NutanixController::class);
});

Route::prefix('master')->name('master.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/barang', BarangController::class);
    Route::post('/barang/tambah/ip-address', [BarangController::class, 'tambahIPAddress'])->name('barang.tambah.ipAddress');	
    Route::resource('/jenis', JenisBarangController::class);
    Route::resource('/pengadaan', PengadaanController::class);
    Route::resource('/lokasi', LokasiController::class);
    Route::resource('/merk', MerkController::class);
	Route::resource('/statusbarang', StatusBarangController::class);
    Route::resource('/tipe', TipeController::class);
    Route::resource('/kategori', KategoriBarangController::class);
    Route::resource('/cluster', ClusterController::class);
    Route::resource('/os', OSController::class);


    Route::prefix('hypervisor')->name('hypervisor.')->group(function ()
    {
        Route::resource('/vmware', VMwareController::class);
        Route::resource('/nutanix', NutanixController::class);
        Route::resource('/powervm/{power_vm_id}/lists', PowerVMListController::class, ['names' => 'powervm.lists']);
        Route::get('powervm/lists', [PowerVMListController::class, 'show'])->name('powervmlists');
        Route::resource('/powervm', PowerVMController::class);
        // Route::resource('/powervm/list', NutanixController::class);
    });
    
    Route::prefix('virtual-machine')->name('virtual-machine.')->group(function ()
    {
        Route::resource('/vm', VirtualMachineController::class);
        Route::resource('/node', NodeController::class);
        Route::resource('/cluster', ClusterController::class);
        Route::resource('/cluster-system', ClusterSystemController::class);
    });

    Route::prefix('import')->name('import.')->group(function ()
    {
        Route::post('/barang', [BarangController::class, 'importMass'])->name('barang');
        Route::post('/vmware', [VMwareController::class, 'importMass'])->name('vmware');
        Route::post('/nutanix', [NutanixController::class, 'importMass'])->name('nutanix');
        Route::post('/powervm', [PowerVMController::class, 'importMass'])->name('powervm');
        Route::post('/powervmlist', [PowerVMListController::class, 'importMass'])->name('powervmlist');
    });
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('/ipAddress/setMgmt', [AjaxController::class, 'setIPMgmt'])->name('setMgmt');
    // Route::post('/barang/store', [BarangsController::class, 'updateJSON'])->name('barang.store');

});

Route::view('/powergrid', 'powergrid-demo');
Route::view('/users', 'index');

resources/views/pages/master/jenis/edit.blade.php
@extends('layouts.app')
@section('css-third')
<style>
    .form-check-input {
        margin-top: -0.7rem; 
    }
</style>
    
@endsection
@section('contents')
<!-- Content Header (Page header) -->
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{ $pageTitle }}</h1>
                </div><!-- /.col -->
                @component('layouts.partials.breadcrumb', [
                    'pageTitle' => $pageTitle
                ])
                    
                @endcomponent
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-title">
                            <h5 class="card-header">Form Edit {{ $pageTitle }}</h5>
                        </div>
                        <div class="card-body">
                            @component('layouts.partials.alert')
                                
                            @endcomponent
                            <form action="{{ route($route, $data->id) }}" method="post">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="nama_jenis_barang">Nama Jenis Barang</label>
                                    {!! Form::text('nama_jenis_barang', $data->nama_jenis_barang, ['class' => 'form-control', 'id' => 'nama_jenis_barang']) !!}
                                </div>
                                <button type="submit" class="btn btn-success float-right">Update {{ $pageTitle }}</button>
                            </form>

                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="m-0">List {{ $pageTitle }}</h5>
                        </div>
                        <div class="card-body">
                            <table id="example" class="display" style="width:100%">
                                <thead>
                                    <tr style=" text-align: center">
                                        <th>Jenis Barang</th>
                                        <th>Dibuat</th>
                                        <th>Diubah</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (app\Models\JenisBarang::get() as $item)
                                    <tr style=" text-align: center">
                                        <td>{{ $item->nama_jenis_barang }}</td>
                                        <td>{{ date('d F Y', strtotime($item->created_at)) }}</td>
                                        <td>{{ date('d F Y', strtotime($item->updated_at)) }}</td>
                                        <td width="40" style="white-space:nowrap; align=right;">
                                            <div class="row">
                                                {{-- <div class="col-4"></div> --}}
                                                <div class="col-6">
													<form action="{{ route('master.jenis.destroy', $item) }}" method="post">
													<a title="edit" class="btn btn-success btn-sm" href="{{ route('master.jenis.edit', $item->id) }}"><i class="fa fa-edit" aria-hidden="true"></i></a>
													<button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>
														@method('delete')
														@csrf
													</form>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
</div>
<!-- /.content -->
@endsection

resources/views/pages/master/jenis/index.blade.php
@extends('layouts.app')
@section('css-third')
<style>
    .form-check-input {
        margin-top: -0.7rem; 
    }
</style>
    
@endsection
@section('contents')
<!-- Content Header (Page header) -->
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{ $pageTitle }}</h1>
                </div><!-- /.col -->
                @component('layouts.partials.breadcrumb', [
                    'pageTitle' => $pageTitle
                ])
                    
                @endcomponent
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-title">
                            <h5 class="card-header">Form {{ $pageTitle }}</h5>
                        </div>
                        <div class="card-body">
                            @component('layouts.partials.alert')
                                
                            @endcomponent
                            <form action="{{ route($route['store']) }}" method="post">
                                @csrf
                                <div class="form-group">
                                    <label for="nama_jenis_barang">Nama Jenis Barang</label>
                                    {!! Form::text('nama_jenis_barang', old('nama_jenis_barang'), ['class' => 'form-control', 'id' => 'nama_jenis_barang']) !!}
                                </div>
                                <button type="submit" class="btn btn-success float-right">Simpan {{ $pageTitle }}</button>
                            </form>

                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="m-0">List {{ $pageTitle }}</h5>
                        </div>
                        <div class="card-body">
                            <table id="example" class="display" style="width:100%">
                                <thead>
                                    <tr style=" text-align: center">
                                        <th>Jenis Barang</th>
                                        <th>Dibuat</th>
                                        <th>Diubah</th>
                                        <th width="40">Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $item)
                                    <tr style=" text-align: center">
                                        <td>{{ $item->nama_jenis_barang }}</td>
                                        <td>{{ date('d F Y', strtotime($item->created_at)) }}</td>
                                        <td>{{ date('d F Y', strtotime($item->updated_at)) }}</td>
                                        <td style="white-space:nowrap; align=right;">
                                            <div class="row">
                                                {{-- <div class="col-4"></div> --}}
                                                <div class="col-6">
													<form action="{{ route('master.jenis.destroy', $item) }}" method="post">
													<a title="edit" class="btn btn-success btn-sm" href="{{ route('master.jenis.edit', $item->id) }}"><i class="fa fa-edit" aria-hidden="true"></i></a>
													<button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>
														@method('delete')
														@csrf
													</form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
</div>
<!-- /.content -->
@endsection