routes/web.php
<?php

use App\Http\Controllers\AjaxController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MerkController;
use App\Http\Controllers\StatusBarangController;
use App\Http\Controllers\TipeController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\ClusterController;
use App\Http\Controllers\ClusterSystemController;
use App\Http\Controllers\LokasiController;
use App\Http\Controllers\VMwareController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PengadaanController;
use App\Http\Controllers\JenisBarangController;
use App\Http\Controllers\MerkBarangController;
use App\Http\Controllers\JenisVirtualMachineController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\NodeController;
use App\Http\Controllers\NutanixController;
use App\Http\Controllers\OSController;
use App\Http\Controllers\PowerVMController;
use App\Http\Controllers\PowerVMListController;
use App\Http\Controllers\VirtualMachineController;
use App\Models\JenisVirtualMachine;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('');
// });

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/barang-guest', [BarangController::class, 'index'])->name('barang.index');
Route::resource('/virtual-machine', VirtualMachineController::class)->only(['index']);

Route::prefix('hypervisor')->name('hypervisor.')->group(function ()
{
    Route::resource('/vmware', VMwareController::class)->only(['index']);
    Route::resource('/nutanix', NutanixController::class)->only(['index']);
    Route::resource('/powervm/{power_vm_id}/lists', PowerVMListController::class, ['names' => 'powervm.lists'])->only(['index']);
    Route::get('powervm/lists', [PowerVMListController::class, 'show'])->name('powervmlists');
    Route::resource('/powervm', PowerVMController::class)->only(['index']);
    // Route::resource('/powervm/list', NutanixController::class);
});

Route::prefix('master')->name('master.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/barang', BarangController::class);
    Route::post('/barang/tambah/ip-address', [BarangController::class, 'tambahIPAddress'])->name('barang.tambah.ipAddress');	
    Route::resource('/jenis', JenisBarangController::class);
    Route::resource('/pengadaan', PengadaanController::class);
    Route::resource('/lokasi', LokasiController::class);
    Route::resource('/merk', MerkController::class);
	Route::resource('/statusbarang', StatusBarangController::class);
    Route::resource('/tipe', TipeController::class);
    Route::resource('/kategori', KategoriBarangController::class);
    Route::resource('/cluster', ClusterController::class);
    Route::resource('/os', OSController::class);


    Route::prefix('hypervisor')->name('hypervisor.')->group(function ()
    {
        Route::resource('/vmware', VMwareController::class);
        Route::resource('/nutanix', NutanixController::class);
        Route::resource('/powervm/{power_vm_id}/lists', PowerVMListController::class, ['names' => 'powervm.lists']);
        Route::get('powervm/lists', [PowerVMListController::class, 'show'])->name('powervmlists');
        Route::resource('/powervm', PowerVMController::class);
        // Route::resource('/powervm/list', NutanixController::class);
    });
    
    Route::prefix('virtual-machine')->name('virtual-machine.')->group(function ()
    {
        Route::resource('/vm', VirtualMachineController::class);
        Route::resource('/node', NodeController::class);
        Route::resource('/cluster', ClusterController::class);
        Route::resource('/cluster-system', ClusterSystemController::class);
    });

    Route::prefix('import')->name('import.')->group(function ()
    {
        Route::post('/barang', [BarangController::class, 'importMass'])->name('barang');
        Route::post('/vmware', [VMwareController::class, 'importMass'])->name('vmware');
        Route::post('/nutanix', [NutanixController::class, 'importMass'])->name('nutanix');
        Route::post('/powervm', [PowerVMController::class, 'importMass'])->name('powervm');
        Route::post('/powervmlist', [PowerVMListController::class, 'importMass'])->name('powervmlist');
    });
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('/ipAddress/setMgmt', [AjaxController::class, 'setIPMgmt'])->name('setMgmt');
    // Route::post('/barang/store', [BarangsController::class, 'updateJSON'])->name('barang.store');

});

Route::view('/powergrid', 'powergrid-demo');
Route::view('/users', 'index');

app/Models/VirtualMachine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class VirtualMachine extends Model
{
    use HasFactory;
    protected $table = 'virtual_machines';
    protected $guarded = [];
    protected $primaryKey = 'id';

    /**
     * Get the Jenis that owns the VirtualMachine
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Jenis(): BelongsTo
    {
        return $this->belongsTo(JenisVirtualMachine::class, 'jenis_virtual_machines_id');
    }

    /**
     * Get the Cluster that owns the VirtualMachine
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Cluster(): BelongsTo
    {
        return $this->belongsTo(Cluster::class, 'cluster_id');
    }

    /**
     * Get the Cluster that owns the VirtualMachine
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function OSS(): BelongsTo
    {
        return $this->belongsTo(OS::class, 'OS');
    }

    /**
     * Get the Node that owns the VirtualMachine
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Node(): BelongsTo
    {
        return $this->belongsTo(Node::class, 'node_id');
    }

    public function UsedSpaced()
    {
        return number_format((($this->vDISK - $this->used_space) / $this->vDISK) * 100, 2, '.', '').'%';
    }

    public function PercentageUsedSpaced()
    {
        return (($this->vDISK - $this->used_space) / $this->vDISK) * 100;
    }

}

app/Http/Controllers/VirtualMachineController.php
<?php

namespace App\Http\Controllers;

use App\Models\JenisVirtualMachine;
use App\Models\VirtualMachine;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class VirtualMachineController extends Controller
{

    public function __construct() {
        $this->view = 'vm';
        $this->moduleName = 'virtual-machine.'.$this->view;
        $this->index = 'master.'.$this->moduleName.'.index';
        $this->store = 'master.'.$this->moduleName.'.store';
        $this->edit = 'master.'.$this->moduleName.'.edit';
        $this->update = 'master.'.$this->moduleName.'.update';
        $this->destroy = 'master.'.$this->moduleName.'.destroy';
        $this->route = [
            'index' => $this->index,
            'store' => $this->store,
            'edit' => $this->edit,
            'update' => $this->update,
            'delete' => $this->destroy,
        ];
        $this->pageTitle = 'Virtual Machine';
        $this->model = new VirtualMachine();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->model->get();
        return view('pages.'.$this->moduleName.'.index', [
            'data' => $data,
            'route' => $this->route,
            'pageTitle' => $this->pageTitle
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request['ip_address'] = $request->ip_address;
        $this->model::create($request->except('_token'));
        return $this->successStore($this->index, $this->pageTitle);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\VirtualMachine  $virtualMachine
     * @return \Illuminate\Http\Response
     */
    public function show(VirtualMachine $virtualMachine)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\VirtualMachine  $virtualMachine
     * @return \Illuminate\Http\Response
     */
    public function edit(VirtualMachine $virtualMachine)
    {
        $data = $this->model::get();
        return view('pages.virtualmachine.edit', [
            'data' => $virtualMachine,
            'table' => $data,
            'select' => [
                'jenis' => JenisVirtualMachine::pluck('nama', 'id')->prepend('Pilih Virtual Machine', '')
            ],
            'pageTitle' => $this->pageTitle,
            'route' => [
                'store' => $this->store,
                'edit' => $this->edit,
                'update' => $this->update,
                'delete' => $this->delete
            ]
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\VirtualMachine  $virtualMachine
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, VirtualMachine $virtualMachine, $id)
    {
        // $meta = array_filter(array_combine($request->key, $request->value), function($value, $key) {
        //     return $key == "" || $value == "" ? false : $value;
        // }, ARRAY_FILTER_USE_BOTH );
        // try {
        //     $virtualMachine->update([
        //         'mac_address' => $request->mac_address,
        //         'used_spaced' => $request->used_spaced,
        //         "nama_vm" => $request->nama_vm,
        //         "deskripsi" => $request->deskripsi,
        //         "ip_address" => $request->ip_address,
        //         "jenis_virtual_machines_id" => $request->jenis_virtual_machines_id,
        //         "core" => $request->core,
        //         "kapasitas_memori" => $request->kapasitas_memori,
        //         "space_hdd" => $request->space_hdd,
        //         "status_power" => $request->status_power,
        //         "os" => $request->os,
        //         "cluster_id" => $request->cluster_id,
        //     ]);
        //     return $this->successUpdate($this->index, $this->pageTitle);
        // } catch (\Throwable $th) {
        //     Log::info('message: ', $th->getMessage());
        //     return $this->failUpdate($this->index, $this->pageTitle);
        // }
        $virtualMachine = $virtualMachine::find($id);
        $virtualMachine->update($request->except('_token'));
        return $this->successUpdate($this->index, $this->pageTitle);

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\VirtualMachine  $virtualMachine
     * @return \Illuminate\Http\Response
     */
    public function destroy(VirtualMachine $virtualMachine, $id)
    {
        $virtualMachine = $virtualMachine::find($id);
        $virtualMachine->delete();
        return $this->successDelete($this->index, $this->pageTitle);
    }
}

resources/views/pages/virtualmachine/edit.blade.php
@extends('layouts.app')
@section('css-third')
<style>
    .form-check-input {
        /* margin-top: -0.3rem; */
    }
</style>

@endsection
@section('contents')
<!-- Content Header (Page header) -->
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{ $pageTitle }}</h1>
                </div><!-- /.col -->
                @component('layouts.partials.breadcrumb', [
                    'pageTitle' => $pageTitle
                ])

                @endcomponent
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div @class([
                    'col-lg-4',
                    'd-none' => Request::segment(1) != 'master'
                ])>
                    <div class="card">
                        <div class="card-title">
                            <h5 class="card-header">Form {{ $pageTitle }}</h5>
                            {{-- <form action="{{ route('master.import.nutanix') }}" method="post" id="import" class="float-right" enctype="multipart/form-data">
                                @csrf
                                {!! Form::file('import', [null]) !!}
                                {!! Form::submit('Import', ['class' => 'btn btn-primary']) !!}
                            </form> --}}
                        </div>
                        <div class="card-body">
                            @component('layouts.partials.alert')

                            @endcomponent
                            <form action="{{ route($route['update'], $data->id) }}" method="post">
                                @csrf
                                @component('copmonents.form.virtualmachine', [
                                    'data' => $data,
                                    'select' => $select
                                ])

                                @endcomponent
                                <button type="submit" class="btn btn-success float-right">Simpan {{ $pageTitle }}</button>
                            </form>
                            {{-- <div class="form-group fieldGroupCopy" style="display: none;">
                                <div class="row">
                                    <div class="col-9 ">
                                        <label for="attribute">Tambah Attribut</label>
                                        <div class="form-group">
                                            <label for="key">Key</label>
                                            <input type="text" name="key[]" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label for="key">value</label>
                                            <input type="text" name="value[]" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group float-right">
                                            <a href="javascript:void(0)" class="btn btn-danger remove"><i class="fas fa-trash"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div> --}}

                        </div>
                    </div>
                </div>
                <div @class([
                    'col-lg-8' => Request::segment(1) == 'master',
                    'col-lg-12' => Request::segment(1) != 'master'
                ])>
                    <div class="card">
                        <div class="card-header">
                            <h5 class="m-0">List {{ $pageTitle }}</h5>
                        </div>
                        <div class="card-body">
                            @component('copmonents.tables.virtualmachine', [
                                'thead' => ['Nama VM', 'Jenis VM', 'Deskripsi', 'IP Address', 'Kapasitas Memori', 'Power State'],
                                'data' => $table,
                                'route' => $route
                            ])

                            @endcomponent
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
</div>
<!-- /.content -->
@endsection
@section('js-third')
    <script>
        $("input:checkbox").on('click', function() {
            // in the handler, 'this' refers to the box clicked on
            var $box = $(this);
            if ($box.is(":checked")) {
                // the name of the box is retrieved using the .attr() method
                // as it is assumed and expected to be immutable
                var group = "input:checkbox[name='" + $box.attr("name") + "']";
                // the checked state of the group/box on the other hand will change
                // and the current value is retrieved using .prop() method
                $(group).prop("checked", false);
                $box.prop("checked", true);
            } else {
                $box.prop("checked", false);
            }
        });

        $(document).ready(function(){
            // membatasi jumlah inputan
            var maxGroup = 10;

            //melakukan proses multiple input
            $(".addMore").click(function(){
                if($('body').find('.fieldGroup').length < maxGroup){
                    var fieldHTML = '<div class="form-group fieldGroup">'+$(".fieldGroupCopy").html()+'</div>';
                    $('body').find('.fieldGroup:last').after(fieldHTML);
                }else{
                    alert('Maximum '+maxGroup+' groups are allowed.');
                }
            });

            //remove fields group
            $("body").on("click",".remove",function(){
                $(this).parents(".fieldGroup").remove();
            });
        });
    </script>
@endsection

resources/views/pages/virtualmachine/index.blade.php
@extends('layouts.app')
@section('css-third')
<style>
</style>

@endsection
@section('contents')
<!-- Content Header (Page header) -->
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{ $pageTitle }}</h1>
                </div><!-- /.col -->
                @component('layouts.partials.breadcrumb', [
                    'pageTitle' => $pageTitle
                ])

                @endcomponent
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-6"><h5 class="m-0">List {{ $pageTitle }}</h5></div>
                                @if (\Request::segment(1) == 'master')
                                <div class="col-6"><button class="btn btn-success float-right" onclick="tambahVM()">Tambah VM</button></div>
                                @endif
                            </div>
                            
                            
                        </div>
                        <div class="card-body">
                            @component('copmonents.tables.virtualmachine', [
                                'thead' => ['Host', 'Nama VM', 'Cluster', 'Jenis VM', 'Deskripsi', 'IP Address', 'Kapasitas Memori', 'Power State'],
                                'data' => $data,
                                'route' => $route
                            ])

                            @endcomponent
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
            @component('copmonents.modal.global.show', [
                'field' => [
                    'nama_vm',
                    'deskripsi',
                    'ip_address',
                    'jenis_virtual_machine',
                    'Core',
                    'kapasitas_memori',
                    'space_hdd',
                    'status_power',
                    'os'
                ],
            ])

            @endcomponent
            @component('copmonents.modal.global.add', [
                'pageTitle' => 'Tambah VM',
                'route' => route($route['store']),
                'form' => 'copmonents.form.virtualmachine',
                'select' => $select,
            ])

            @endcomponent
            @component('copmonents.modal.global.edit', [
                'pageTitle' => 'VM',
                'data' => $data,
                'route' => null,
                'form' => 'copmonents.form.virtualmachine',
                'select' => $select,
            ])

            @endcomponent
        </div><!-- /.container-fluid -->
    </div>
</div>
<!-- /.content -->
@endsection
@section('js-third')
    <script>

        function tambahVM() {
            $('#modal-tambah').modal()
            
        }

        function ubah(params) {
            $('#modal-edit').modal()
            $("form#update").attr('action', "{{ url('master/virtual-machine/') }}/"+params.id+"");
            $('input#nama_vm').val(params.nama_vm)
            $('textarea#deskripsi').val(params.deskripsi)
            $('select[name=jenis_virtual_machines_id]').val(params.jenis_virtual_machines_id);
            $('select[name=barang_id]').val(params.barang_id);
            $( "input#"+params.status_power+"").prop('checked', true);
            $('input#ip_address').val(params.ip_address)
            $('input#core').val(params.core)
            $('input#kapasitas_memori').val(params.kapasitas_memori)
            $('input#space_hdd').val(params.space_hdd)
            $('input#os').val(params.os)
            $('input#mac_address').val(params.mac_address)
            $('input#used_spaced').val(params.used_spaced)
        }

function lihat(params) {
    $('#modal-show').modal();
    console.log(params.cluster);

    // var html = '';
    // $.each(JSON.parse(params.meta), function (indexInArray, valueOfElement) {
    //     html += '<div class="row">'
    //     html += '<div class="col-5"> <strong>'+indexInArray+'</strong> </div>'
    //     html += '<div class="col-2"> : </div>'
    //     html += '<div class="col-5"> '+valueOfElement+' </div>'
    //     html += '</div>'
    // });
    var html = '<ul style="list-style-type: none;padding-left: 0;">';
            html += '<li><strong>Mac Address</strong>: '+params.mac_address+'</li>'
            html += '<li><strong>Used Spaced</strong>: '+params.used_spaced+'</li>'
            html += '<li><strong>Cluster</strong>: '+params.cluster.name+'</li>'
        html += '<ul>';
    $('td#nama_vm').html(params.nama_vm);
    $('td#deskripsi').html(html);
    $('td#ip_address').html(params.ip_address);
    $('td#jenis_virtual_machine').html(params.jenis.nama);
    $('td#Core').html(params.core);
    $('td#kapasitas_memori').html(params.kapasitas_memori);
    $('td#space_hdd').html(params.space_hdd);
    $('td#status_power').html(params.status_power);
    $('td#os').html(params.os);
}

        $("input:checkbox").on('click', function() {
            // in the handler, 'this' refers to the box clicked on
            var $box = $(this);
            if ($box.is(":checked")) {
                // the name of the box is retrieved using the .attr() method
                // as it is assumed and expected to be immutable
                var group = "input:checkbox[name='" + $box.attr("name") + "']";
                // the checked state of the group/box on the other hand will change
                // and the current value is retrieved using .prop() method
                $(group).prop("checked", false);
                $box.prop("checked", true);
            } else {
                $box.prop("checked", false);
            }
        });
        $(document).ready(function(){
            // membatasi jumlah inputan
            var maxGroup = 10;

            //melakukan proses multiple input
            $(".addMore").click(function(){
                if($('body').find('.fieldGroup').length < maxGroup){
                    var fieldHTML = '<div class="form-group fieldGroup">'+$(".fieldGroupCopy").html()+'</div>';
                    $('body').find('.fieldGroup:last').after(fieldHTML);
                }else{
                    alert('Maximum '+maxGroup+' groups are allowed.');
                }
            });

            //remove fields group
            $("body").on("click",".remove",function(){
                $(this).parents(".fieldGroup").remove();
            });
        });
    </script>
@endsection